### ISSUE TITLE
Instant bomb when I click on the Map button

### ISSUE THREAD

**Issue by tre4b** [Snoothy/UCR#211]
Hangs briefly the just crashes.

When I first installed the program it did nothing.   Then once I clicked on the button and pressed a key on a keyboard and it mapped it.  Tried with a different key and it crashed and now it only crashes.

No idea why, will download again tomorrow but let me know if you want logs to look at or something...

**Comment by tre4b** [comment]
This seems to be related to attempting to map a mouse button.  Which I was doing by mistake by double clicking the button. 

If I choose The mapping button and press either my keyboard or the numpad I also have it finds a button successfully.  If I press any mouse button then the whole program locks up and needs to be closed with task manager.

The Mouse is a Logitech G502 which is seen through an input device called M: Logitech USB Receiver

**Comment by tre4b** [comment]
Using mouse buttons already mapped through the Logitech mouse software the crash does not happen as it sees the mapping as the Mapped Key and not as the underlying mouse button.  buttons 1,2,3.

**Comment by tre4b** [comment]
Just tried an Axis too and this too crashed.

**Comment by Tactile-Taco** [comment]
I'm getting the same problem with my joystick. This is in the log:
```
2021-02-25 17:38:40.1275 FATAL Could not find device Handle VID_044F&PID_B10A, Instance 0 System.Exception: Could not find device Handle VID_044F&PID_B10A, Instance 0
   at SharpDX_DirectInput.DeviceLibrary.DiDeviceLibrary.GetInputDeviceIdentifier(DeviceDescriptor deviceDescriptor)
   at SharpDX_DirectInput.DiDeviceHandler..ctor(DeviceDescriptor deviceDescriptor, EventHandler`1 deviceEmptyHandler, EventHandler`1 bindModeHandler, IInputDeviceLibrary`1 deviceLibrary)
   at SharpDX_DirectInput.SharpDX_DirectInput.SetDetectionMode(DetectionMode detectionMode, DeviceDescriptor deviceDescriptor, Action`4 callback)
   at HidWizards.IOWrapper.Core.IOController.SetDetectionMode(DetectionMode detectionMode, ProviderDescriptor providerDescriptor, DeviceDescriptor deviceDescriptor, Action`4 callback)
   at HidWizards.UCR.Core.Managers.BindingManager.BeginBindMode(DeviceBinding deviceBinding) in D:\Projects\UCR\UCR.Core\Managers\BindingManager.cs:line 56
   at HidWizards.UCR.Core.Models.Binding.DeviceBinding.EnterBindMode() in D:\Projects\UCR\UCR.Core\Models\Binding\DeviceBinding.cs:line 192
   at HidWizards.UCR.Views.Controls.DeviceBindingControl.BindButton_OnClick(Object sender, RoutedEventArgs e)
   at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs args, Boolean trusted)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run(Window window)
   at HidWizards.UCR.App.Main()
```

**Comment by Tactile-Taco** [comment]
It seems to happen when my joystick isn't being detected or sometimes when I reconnect it to a different port. Wish it wouldn't cause a fatal error.

**Comment by evilC** [comment]
This is a known issue and is as yet unresolved. I think there may be a waiting fix in an unreleased branch, but for now, to work around, just use the manual bind (Click the `...`)
