### ISSUE TITLE
Help: vgemclient.dll not found

### ISSUE THREAD

**Issue by fohfuu** [Snoothy/UCR#258]
UCR.exe refuses to run and I don't know why. It fails to see ViGem no matter  what I do.

After extracting UCR at first, I tried to run it without setting it up, and it did open but entirely empty (duh). I went through the steps on the wiki, and I installed vJoy and Interceptions. I had already installed ViGem earlier, but decided to uninstall and reinstall using the link from the wiki, just in case. I un/reinstalled it to check it was working properly (restarting after each step, ofc). It is visible in Installed Programs. It is installed.

However, now on opening UCR.exe, it always gives the same log.

`2021-11-20 01:10:53.9389 INFO Launching UCR 
2021-11-20 01:10:54.0483 ERROR Failed to load context.xml 
2021-11-20 01:10:54.2982 DEBUG Start bind mode 
2021-11-20 01:10:54.4076 FATAL Unable to load DLL 'vigemclient.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E) System.DllNotFoundException: Unable to load DLL 'vigemclient.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at Nefarius.ViGEm.Client.ViGEmClient.vigem_disconnect(IntPtr vigem)
   at Nefarius.ViGEm.Client.ViGEmClient.Dispose(Boolean disposing)
   at Nefarius.ViGEm.Client.ViGEmClient.Finalize()`

I have reinstalled it multiple times, did the entire UCR setup over multiple times, repaired Visual C++ x64 in Programs And Features and installed x84, running everything I could as admin, and nothing has changed. It just appends another failure to the log when I try to open it from File Explorer or even from Command Prompt.

If anyone has any idea what steps I could take to fix this - taking into account the things I've already tried - thanks in advance.

Edition	Windows 10 Home (64, x64 processor)
Version	21H1
OS build	19043.1348
Experience	Windows Feature Experience Pack 120.2212.3920.0

**Comment by akici** [comment]
@fohfuu could you find a solution? I got the same problem.

**Comment by fohfuu** [comment]
@akici unfortunately not :( I gave up.
